var map;
var currentFlashMovie;
var selectedObjects = new Object();
var taskDetails = new Array();
var vehiclesToSelect = new Array();
var vehiclesToSelectDepo = new Array();
var activity = new Array();
var allVehicles = new Array();
var handheldsToSelect = new Array();
var allHandhelds = new Array();
var isMapViewType = true;
var isFlex = true;
var vehicleIconSize = 50;
var isVehicleIconRotation = true;
var isZoomMode = typeof(isVehicleZoomMode) != "undefined" ? isVehicleZoomMode : false; //from mapping.jsp
var disableZoomWhileRefresh = false;
var isVehicleZoomClickProcessingAllowed = true;
var zoomedVehicleId = null;
var zoomedVehicle = null;
//var drawControl;
var msvePlaces = null;
//var polyWkt = null;
var myLoc = null;
var hoverOverPoiAllowed = false;
var poiAreaColoured = false;
var hoverOverAoiAllowed = false;
var aoiAreaColoured = false;
var choosePoiAreaColour = false;
var chooseAoiAreaColour = false;
var mapRezoom = true;
var rightClickOnMapListener;