ALTER TABLE `area`  DROP FOREIGN KEY `FK1F44AD2E63157A`;
ALTER TABLE `area`  CHANGE COLUMN `country_id` `country_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `country` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `area`  ADD CONSTRAINT `FK1F44AD2E63157A` FOREIGN KEY (`country_id`) REFERENCES `country` (`id`);

ALTER TABLE `city` DROP FOREIGN KEY `FK200D8BEA1B671A`;
ALTER TABLE `city` CHANGE COLUMN `area_id` `area_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `area` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `city`  ADD CONSTRAINT `FK200D8BEA1B671A` FOREIGN KEY (`area_id`) REFERENCES `area` (`id`);

ALTER TABLE `city`
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `invoice` DROP FOREIGN KEY `FKD80EDB0D26C218D3`;
ALTER TABLE `invoice` CHANGE COLUMN `booking_id` `booking_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `booking` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `invoice`  ADD CONSTRAINT `FKD80EDB0D26C218D3` FOREIGN KEY (`booking_id`) REFERENCES `booking` (`id`);

ALTER TABLE `invoice` DROP FOREIGN KEY `FKD80EDB0DA5EBA800`;
ALTER TABLE `invoice` CHANGE COLUMN `supplier_id` `supplier_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `supplier` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `invoice`  ADD CONSTRAINT `FKD80EDB0DA5EBA800` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`id`);


ALTER TABLE `customer` DROP FOREIGN KEY `FK27FBE3FEDE3D72D6`;
ALTER TABLE `invoice` DROP FOREIGN KEY `FKD80EDB0D909B3C98`;
ALTER TABLE `invoice` DROP FOREIGN KEY `FKD80EDB0D9DE51795`;
ALTER TABLE `customer` CHANGE COLUMN `person_id` `person_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `invoice` CHANGE COLUMN `executor_id` `executor_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `invoice` CHANGE COLUMN `responsible_id` `responsible_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `user` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `customer`  ADD CONSTRAINT `FK27FBE3FEDE3D72D6` FOREIGN KEY (`person_id`) REFERENCES `user` (`id`);
ALTER TABLE `invoice`  ADD CONSTRAINT `FKD80EDB0D909B3C98` FOREIGN KEY (`executor_id`) REFERENCES `user` (`id`);
ALTER TABLE `invoice`  ADD CONSTRAINT `FKD80EDB0D9DE51795` FOREIGN KEY (`responsible_id`) REFERENCES `user` (`id`);



ALTER TABLE `invoice` DROP FOREIGN KEY `FKD80EDB0D534D9626`;
ALTER TABLE `invoice` DROP FOREIGN KEY `FKD80EDB0D17337BA8`;

ALTER TABLE `customer` DROP FOREIGN KEY `FK27FBE3FE18C83F26`;
ALTER TABLE `customer` DROP FOREIGN KEY `FK27FBE3FEDF6BDCE0`;


ALTER TABLE `invoice` DROP INDEX `FKD80EDB0D534D9626`;


ALTER TABLE `customer` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `invoice` CHANGE COLUMN `consumer_id` `consumer_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `invoice` CHANGE COLUMN `emploer_id` `employer_id` INT(11) NULL DEFAULT NULL;

ALTER TABLE `customer` CHANGE COLUMN `oldRecord_id` `oldRecord_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `customer` CHANGE COLUMN `headCustomer_id` `headCustomer_id` INT(11) NULL DEFAULT NULL;

ALTER TABLE `invoice` ADD INDEX `FKD80EDB0D534D9626` (`employer_id`);

ALTER TABLE `invoice`  ADD CONSTRAINT `FKD80EDB0D534D9626` FOREIGN KEY (`employer_id`) REFERENCES `customer` (`id`);
ALTER TABLE `invoice`  ADD CONSTRAINT `FKD80EDB0D17337BA8` FOREIGN KEY (`consumer_id`) REFERENCES `customer` (`id`);

ALTER TABLE `customer`  ADD CONSTRAINT `FK27FBE3FE18C83F26` FOREIGN KEY (`oldRecord_id`) REFERENCES `customer` (`id`);
ALTER TABLE `customer`  ADD CONSTRAINT `FK27FBE3FEDF6BDCE0` FOREIGN KEY (`headCustomer_id`) REFERENCES `customer` (`id`);





ALTER TABLE `contact`  DROP FOREIGN KEY `FK9BEFBC0073B85F1C`;
ALTER TABLE `contact` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `contact`  CHANGE COLUMN `oldRecord_id` `oldRecord_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `contact`  ADD CONSTRAINT `FK9BEFBC0073B85F1C` FOREIGN KEY (`oldRecord_id`) REFERENCES `contact` (`id`);


ALTER TABLE `contact`  DROP FOREIGN KEY `FK9BEFBC009064C080`;
ALTER TABLE `profession` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `contact`  CHANGE COLUMN `profession_id` `profession_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `contact`  ADD 	CONSTRAINT `FK9BEFBC009064C080` FOREIGN KEY (`profession_id`) REFERENCES `profession` (`id`);

ALTER TABLE `supplier`  DROP FOREIGN KEY `FKA0B65DEC6B7F45E0`;
ALTER TABLE `currency` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `supplier`  CHANGE COLUMN `currency_id` `currency_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `supplier`  ADD 	CONSTRAINT `FKA0B65DEC6B7F45E0` FOREIGN KEY (`currency_id`) REFERENCES `currency` (`id`);


ALTER TABLE `customer`  DROP FOREIGN KEY `FK27FBE3FEBA493A54`;
ALTER TABLE `orgForm` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `customer`  CHANGE COLUMN `orgForm_id` `orgForm_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `customer`  ADD 	CONSTRAINT `FK27FBE3FEBA493A54` FOREIGN KEY (`orgForm_id`) REFERENCES `orgform` (`id`);

ALTER TABLE `customer`
CHANGE COLUMN `area` `area` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `city` `city` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `country` `country` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `region` `region` INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN `localityType` `localityType` INT(11) NULL DEFAULT NULL ;


ALTER TABLE `user`  DROP FOREIGN KEY `FK285FEBA570BA5D`;
RENAME TABLE `invoicefilter` TO `invoice_filter`;
ALTER TABLE `invoice_filter` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `user`  CHANGE COLUMN `invoicefilter_fk` `invoice_filter_fk` INT(11) NULL DEFAULT NULL;
ALTER TABLE `user`  ADD 	CONSTRAINT `FK285FEBA570BA5D` FOREIGN KEY (`invoice_filter_fk`) REFERENCES `invoice_filter` (`id`);



ALTER TABLE `invoiceitem`  DROP FOREIGN KEY `FK30037BC05BA03853`;
ALTER TABLE `payment`  DROP FOREIGN KEY `FK3454C9E65BA03853`;
ALTER TABLE `shipment`  DROP FOREIGN KEY `FKE513D5BA5BA03853`;
RENAME TABLE `invoiceitem` TO `invoice_item`;

ALTER TABLE `invoice` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `invoice_item`  CHANGE COLUMN `INVOICE_ID` `INVOICE_ID` INT(11) NULL DEFAULT NULL;
ALTER TABLE `payment`  CHANGE COLUMN `INVOICE_ID` `INVOICE_ID` INT(11) NULL DEFAULT NULL;
ALTER TABLE `shipment`  CHANGE COLUMN `INVOICE_ID` `INVOICE_ID` INT(11) NULL DEFAULT NULL;

ALTER TABLE `invoice_item`  ADD  CONSTRAINT `FK30037BC05BA03853` FOREIGN KEY (`INVOICE_ID`) REFERENCES `invoice` (`id`);
ALTER TABLE `payment`  ADD  CONSTRAINT `FK3454C9E65BA03853` FOREIGN KEY (`INVOICE_ID`) REFERENCES `invoice` (`id`);
ALTER TABLE `shipment`  ADD  CONSTRAINT `FKE513D5BA5BA03853` FOREIGN KEY (`INVOICE_ID`) REFERENCES `invoice` (`id`);

ALTER TABLE `modeldescription`
CHANGE COLUMN `id` `id` INT(11) NOT NULL FIRST;
RENAME TABLE `modeldescription` TO `model_description`;

ALTER TABLE `payment` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;

RENAME TABLE `pressuresensor` TO `pressure_sensor`;



RENAME TABLE `shipmentmediator` TO `shipment_mediator`;
ALTER TABLE `pressure_sensor`  DROP FOREIGN KEY `FKEC3F9A7F8B9D8E34`;
ALTER TABLE `production`  DROP FOREIGN KEY `FKDF4ECCD98B9D8E34`;
ALTER TABLE `shipment_mediator`  DROP FOREIGN KEY `FK9A5176CDCE3AA7CE`;

ALTER TABLE `invoice_item` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `pressure_sensor`  CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `production`  CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `shipment_mediator`  CHANGE COLUMN `INVOICE_ITEM_ID` `INVOICE_ITEM_ID` INT(11)  NULL DEFAULT NULL;

ALTER TABLE `pressure_sensor`  ADD 	CONSTRAINT `FKEC3F9A7F8B9D8E34` FOREIGN KEY (`id`) REFERENCES `invoice_item` (`id`);
ALTER TABLE `production`  ADD 	CONSTRAINT `FKDF4ECCD98B9D8E34` FOREIGN KEY (`id`) REFERENCES `invoice_item` (`id`);
ALTER TABLE `shipment_mediator`  ADD CONSTRAINT `FK9A5176CDCE3AA7CE` FOREIGN KEY (`INVOICE_ITEM_ID`) REFERENCES `invoice_item` (`id`);



RENAME TABLE `productionprice` TO `production_price`;

ALTER TABLE `production_price`
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `region`
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;

ALTER TABLE `shipment_mediator`
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;



ALTER TABLE `shipment_mediator`  DROP FOREIGN KEY `FK9A5176CDA2D6D8E1`;
ALTER TABLE `shipment` CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST;
ALTER TABLE `shipment_mediator`  CHANGE COLUMN `SHIPMENT_ID` `SHIPMENT_ID` INT(11) NULL DEFAULT NULL;
ALTER TABLE `shipment_mediator`  ADD 	CONSTRAINT `FK9A5176CDA2D6D8E1` FOREIGN KEY (`SHIPMENT_ID`) REFERENCES `shipment` (`id`);






















ALTER TABLE `invoice`	ADD COLUMN `addition_to_price` DECIMAL(10,2) NOT NULL DEFAULT '00.00';
ALTER TABLE `invoice`	ADD COLUMN `nds_percent` DECIMAL(10,2) NOT NULL DEFAULT '00.00';
ALTER TABLE `invoice`	ADD COLUMN `payment_percent` DECIMAL(10,2) NOT NULL DEFAULT '00.00';
ALTER TABLE `invoice`	ADD COLUMN `total` DECIMAL(10,2) NOT NULL DEFAULT '00.00';
ALTER TABLE `invoice`	ADD COLUMN `sum` DECIMAL(10,2) NOT NULL DEFAULT '00.00';
ALTER TABLE `invoice`	ADD COLUMN `shipment_percent` DECIMAL(10,2) NOT NULL DEFAULT '00.00';
ALTER TABLE `invoice`	ADD COLUMN `total_payments` DECIMAL(10,2) NOT NULL DEFAULT '00.00';




ALTER TABLE `invoice`	ADD COLUMN `is_any_goods_shipped` CHAR(1) NOT NULL  DEFAULT 'N';
ALTER TABLE `invoice`	ADD COLUMN `is_delivery_made` CHAR(1) NOT NULL  DEFAULT 'N';
ALTER TABLE `invoice`	ADD COLUMN `is_payment_made` CHAR(1) NOT NULL  DEFAULT 'N';

ALTER TABLE `currency`
CHANGE COLUMN `exchangeRate` `exchangeRate` DECIMAL(19,2) NOT NULL DEFAULT '00.00' ;

ALTER TABLE `invoice`
CHANGE COLUMN `NDS` `NDS` DECIMAL(19,2) NOT NULL DEFAULT '00.00' ;

ALTER TABLE `invoice`
CHANGE COLUMN `exchangeRate` `exchangeRate` DECIMAL(19,2) NOT NULL DEFAULT '00.00' ;

ALTER TABLE `invoice`
CHANGE COLUMN `paymentOnTheNitice` `paymentOnTheNotice` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `invoice`
CHANGE COLUMN `postPay` `postPay` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `invoice`
CHANGE COLUMN `prepayment` `prepayment` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `invoice_item`
CHANGE COLUMN `additionalCost` `additionalCost` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `invoice_item`
CHANGE COLUMN `cost` `cost` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `invoice_item`
CHANGE COLUMN `price` `price` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `invoice_item`
CHANGE COLUMN `sellingPrice` `selling_price` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `invoice_item`
CHANGE COLUMN `additionalCost` `additional_cost` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `invoice_item`
CHANGE COLUMN `transportationCost` `transportation_cost` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

RENAME TABLE `optionsprice` TO `options_price`;

ALTER TABLE `options_price`
CHANGE COLUMN `cost` `cost` DECIMAL(19,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `payment`
CHANGE COLUMN `exchangeRate` `amount` DECIMAL(8,6) NOT NULL DEFAULT '1.00';



ALTER TABLE `payment`
CHANGE COLUMN `paymentSum` `payment_sum` DECIMAL(12,2) NOT NULL DEFAULT '00.00';

RENAME TABLE `pricefirstpart` TO `price_first_part`;

ALTER TABLE `price_first_part`
CHANGE COLUMN `cost` `cost` DECIMAL(12,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `price_first_part`
CHANGE COLUMN `price` `price` DECIMAL(12,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `price_first_part`
CHANGE COLUMN `priceTmp` `price_tmp` DECIMAL(12,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `price_first_part`
CHANGE COLUMN `costTmp` `cost_tmp` DECIMAL(12,2) NOT NULL DEFAULT '00.00';



ALTER TABLE `production_price`
CHANGE COLUMN `cost` `cost` DECIMAL(12,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `production_price`
CHANGE COLUMN `price` `price` DECIMAL(12,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `supplier`
ADD COLUMN `second_chief_fio` VARCHAR(255) NULL DEFAULT NULL ,
ADD COLUMN `second_chief` VARCHAR(255) NULL DEFAULT NULL ;


ALTER TABLE `options_price`
CHANGE COLUMN `cost` `cost` DECIMAL(12,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `options_price`
CHANGE COLUMN `price` `price` DECIMAL(12,2) NOT NULL DEFAULT '00.00';

ALTER TABLE `price_first_part`
CHANGE COLUMN `model` `model` INT(11) NOT NULL;




